version: '3.8'

services:
  chess-fetcher:
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: chess-data-fetcher
    volumes:
      - ./data:/data
      - ./Figures:/app/Figures
    environment:
      - OUTPUT_CSV=/data/daily_chess_stats_GB.csv
      - CONCURRENT_REQUESTS=100  # Adjust based on your VM specs
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    mem_limit: 4g  # Adjust based on your VM
    cpus: 2.0      # Adjust based on your VM
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.chess.com/pub/country/GB', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chess_data:
    driver: local